name: Deploy to firebase
on:
  push:
    branches:
      - master
    paths:
      - "web/**"
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      # installing packages from github repository bug fix for actions
      # https://github.community/t5/GitHub-Actions/Installing-an-npm-module-from-a-private-GitHub-repository/td-p/42821
      - name: Install dependencies
        working-directory: ./web
        run: |
          sed -i 's/ssh:\/\/git@github.com/https:\/\/${{ secrets.NODE_AUTH_TOKEN }}:x-oauth-basic@github.com/g' package.json
          cat package.json
          npm install

      - name: Check current directory
        working-directory: ./web/node_modules
        run: echo $(ls)

      - name: Check parent directory
        run: echo $(ls)

      - name: Take prd build
        working-directory: ./web
        run: npm run build
        env:
          NODE_ENV: production

      - name: Save build files
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: web/build

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Download build files
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: web/dist

      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./web

      - name: Perform lighthouse audit
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: https://readme-later.web.app
          # budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

      # custom action example
      # - name: Perform lighthouse audit
      #   id: lighthouse
      #   uses: ./.github/actions/lighthouse.test
      #   with:
      #     url: https://readme-later.web.app
